[workspace]
resolver = "2"
members = [
    "crates/openmassspec-io",
    "crates/openmassspec-io-cli",
    "crates/openmassspec-io-py",
]

[workspace.package]
version = "2.0.0"
edition = "2021"
rust-version = "1.95"
authors = ["Nathan Riley <git@nathanriley.com>"]
license = "Apache-2.0"
repository = "https://github.com/Sigilweaver/OpenMassSpec"
homepage = "https://sigilweaver.app/openmassspec/"
documentation = "https://sigilweaver.app/openmassspec/docs/"

[workspace.dependencies]
openmassspec-core = "2.0.0"
opentfraw = "2.0.0"
opentimstdf = "2.0.0"
openwraw = "3.0.0"
openaraw = "0.2.0"
opensxraw = "0.3.0"
openszraw = "0.2.0"

[workspace.lints.rust]
unsafe_code = "forbid"
